FROM whshk/nifi
COPY nifi-opc-ua-bundles/nifi-opcua-nar/target/nifi-opcua.nar /opt/nifi/nifi-current/lib/
COPY mysql-connector-java-5.1.18.jar /opt/nifi/nifi-current/lib/
COPY nifi-mqtt-nar-1.9.2.nar /opt/nifi/nifi-current/lib/ 
